  services:                                                                                                                 
    app:                                                                                                                    
      build:                                                                                                                
        context: .                                          
        args:
          VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
          VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      image: r19-rtk-zustand-todo
      container_name: r19-rtk-zustand-todo
      ports:
        - "3002:80"
      restart: unless-stopped